import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { SITE_ORIGIN, pageDefinitions } from "../src/config/pageDefinitions.js";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const legacyDir = path.join(rootDir, "legacy-html");
const outputFile = path.join(rootDir, "src", "data", "legacyPages.generated.js");
const sitemapFile = path.join(rootDir, "public", "sitemap.xml");

function getTagContents(html, tagName) {
  const pattern = new RegExp(`<${tagName}\\b[^>]*>([\\s\\S]*?)<\\/${tagName}>`, "gi");
  return [...html.matchAll(pattern)].map((match) => match[1].trim());
}

function getTitle(html, fallback) {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? match[1].replace(/\s+/g, " ").trim() : fallback;
}

function getBody(html) {
  const match = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const body = match ? match[1] : html;
  return body.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "").trim();
}

function normalizeSource(value) {
  return value.replace(/\r\n/g, "\n").trim();
}

function toJs(value) {
  return JSON.stringify(value);
}

const pages = {};

for (const definition of pageDefinitions) {
  if (definition.kind === "react") continue;

  const filename = path.join(legacyDir, definition.file);
  const html = await readFile(filename, "utf8");

  pages[definition.id] = {
    id: definition.id,
    file: definition.file,
    title: definition.title || getTitle(html, definition.id),
    description: definition.description,
    styles: normalizeSource(getTagContents(html, "style").join("\n\n")),
    scripts: getTagContents(html, "script").map(normalizeSource),
    body: normalizeSource(getBody(html))
  };
}

const generated = `// This file is generated by scripts/generate-pages.mjs.
// Edit files in legacy-html/ or src/config/pageDefinitions.js, then run npm run build.

export const legacyPages = ${toJs(pages)};
`;

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, generated, "utf8");

const lastmod = new Date().toISOString().slice(0, 10);
const urls = pageDefinitions
  .map((definition) => {
    const loc = `${SITE_ORIGIN}${definition.path === "/" ? "/" : definition.path}`;
    return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${definition.path === "/" ? "1.0" : "0.8"}</priority>
  </url>`;
  })
  .join("\n");

await writeFile(
  sitemapFile,
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`,
  "utf8"
);
